server:
  port: 8090

spring:
  application:
    name: mscv-profile

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:3306/management_booking_social_media
    username: admin
    password: *
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  instance:
    hostname: localhost
  client:
    server-url:
      defaultZone: http://localhost:${server.port}/eureka/