server:
  port: 8090
spring:
  application:
    name: msvc-profile
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  instance:
    hostname: localhost
  client:
    server-url:
      defaultZone: http://localhost:${server.port}/eureka/